### ISSUE TITLE
mpdf.fsf.FSF.get_2darray does not give exactly centred PSF image

### ISSUE THREAD

**Issue by jzabl** [musevlt/mpdaf#11]
**Expected behaviour:** 
I would expect that mpdf.fsf.FSF.get_2darray does return a centred PSF array/image, if in `get_2darray(self, lbda, shape, center=None):` center is chosen as None.

**Actual behaviour:**
The returned PSF image seems to be offset by 0.5 pixels from the centre both in y and x.

**Reason:**
The problem is here, I think: 
https://github.com/musevlt/mpdaf/blob/bb177d603f7e135b89e8bd2638f6301890464a67/lib/mpdaf/MUSE/fsf.py#L90

Both from the y, x coordinates 0.5 should be subtracted.

**Comment by RolandBacon** [comment]
Solved in commit #9834286
