### ISSUE TITLE
Bug in error calculation in Spectrum.mean

### ISSUE THREAD

**Issue by jzabl** [musevlt/mpdaf#13]
The appears to be a bug in the error propagation in Spectrum.mean().

https://github.com/musevlt/mpdaf/blob/983428674ce44cd2595b0b90e952aa333c75e32c/lib/mpdaf/obj/spectrum.py#L766

It is currently: 
```python
flux, wsum = np.ma.average(self.data[lambda_slice], returned=True)
if self.var is not None:
     err_flux = np.sqrt(np.ma.sum(self.var[lambda_slice])) / wsum**2
```
But it should be:

```python
    err_flux = np.sqrt(np.ma.sum(self.var[lambda_slice])) / wsum
```
or 
```python
    err_flux = np.sqrt(np.ma.sum(self.var[lambda_slice]) / wsum**2.)
```

This indirectly also affects `Spectrum.abmag_band`

**Comment by RolandBacon** [comment]
Thanks for the check. Correction implemented.
