### ISSUE TITLE
Variance array units.

### ISSUE THREAD

**Issue by Vital-Fernandez** [musevlt/mpdaf#19]
My appologies if I missed this information on the documentation. I am working with a MUSE data cube which includes the variance layer from reduction pipeline.

A spectrum object from this cube has the units specified as `'1e-20 erg / (Angstrom cm2 s)'`. This is the expected value.

However, I wonder if the variance array provided by the `spectrum_object.var` has also also these units or what we actually have is the squared of the flux units.

Thank you very much for your work.

**Comment by RolandBacon** [comment]
The array unit are of variance type, i.e. the squared of the flux unit (1.e-20 erg.s-1.cm-2.A-1)**2

-------------------------------------------
Roland Bacon
CRAL - Observatoire de Lyon
9, avenue Charles André
69230 Saint-Genis-Laval
tel: +33 478 86 85 59
mobile: +33 608 09 14 27

**Comment by Vital-Fernandez** [comment]
Thank you very much.
