### ISSUE TITLE
Documentation obj.cube_combine - error propagation

### ISSUE THREAD

**Issue by Knusper** [musevlt/mpdaf#2]
I think the sentence

> The variance is the mean of the variances of the N individual exposures divided by N**2.

should read

> The variance is the sum of the variances of the N individual exposures divided by N**2.

because the mean of the variances would be `sum(sigma**2)/N`, and this divided by `N**2` would be `sum(sigma**2)/N**3`?

**Comment by saimn** [comment]
Hi Christian,

Yes you're right. The docstring is actually mentioning the sum (https://mpdaf.readthedocs.io/en/latest/api/mpdaf.obj.CubeList.html#mpdaf.obj.CubeList.combine), but the paragraph in the documentation page (https://mpdaf.readthedocs.io/en/latest/cubelist.html#examples) is wrong.
