### ISSUE TITLE
Memory Error when dealing with large cubes 

### ISSUE THREAD

**Issue by bobyokidoki** [musevlt/mpdaf#3]
The ''cube'' class throws a Memory Error when dealing with large MUSE cube (1077, 566, 3802) even using a large amount of memory (64 GB) on a machine with 48 cores.

**Comment by saimn** [comment]
Hi,
Do you get the MemoryError when reading the cube or when doing some operation with it ? Mpdaf does nothing fancy to read the data, it just uses astropy's io.fits.
And your cube is actually quite big: when stored as float32 it should take something like `1077 * 566 * 3802 * 4 / 1024**3` x2 (DATA and STAT), so ~17GB. And when reading the cube Mpdaf reads as float64, so it will take the double in memory (plus the mask array). So you should be able to read the cube, but doing any operation on the full cube will likely lead to a MemoryError.
There is one option to use less memory, which is to read the cube as float32 with `Cube(..., convert_float64=False)`.

**Comment by saimn** [comment]
Please reopen if needed.
